### ISSUE TITLE
Unable to configure Aleph Zero Network

### ISSUE THREAD

**Issue by CocDap** [subsquid/squid-sdk#204]
**Describe the bug**
 I am unable to run Aleph Zero Processor. What should I configure ? I dont find out any template regarding Aleph Zero Template 

**Environment**
 - package.json
 ```{
  "name": "squid",
  "private": true,
  "engines": {
    "node": ">=16"
  },
  "scripts": {
    "build": "rm -rf lib && tsc"
  },
  "dependencies": {
    "@subsquid/archive-registry": "^3.1.0",
    "@subsquid/graphql-server": "^3.3.2",
    "@subsquid/ss58": "^0.1.4",
    "@subsquid/substrate-processor": "^2.4.1",
    "@subsquid/typeorm-migration": "^0.1.6",
    "@subsquid/typeorm-store": "^0.2.2",
    "dotenv": "^16.0.0",
    "pg": "8.9.0",
    "typeorm": "^0.3.17"
  },
  "devDependencies": {
    "@subsquid/substrate-metadata-explorer": "^1.1.2",
    "@subsquid/substrate-typegen": "^2.2.1",
    "@subsquid/typeorm-codegen": "^0.3.3",
    "@types/node": "^18.11.18",
    "typescript": "^4.9.5"
  }
}
```

 - node.js version : v20.8.0
 - npm version: 10.1.0
 - OS version : MacOS 13.4.1 (c) 

** My configuration**
 - processor.ts
```
....
export const processor = new SubstrateBatchProcessor()
  .setDataSource({
    archive: lookupArchive('aleph-zero', {release: 'ArrowSquid'}),
    chain: "wss://ws.azero.dev",
  })
  .addEvent("Balances.Transfer", {
    data: {
      event: {
        args: true,
        extrinsic: {
          hash: true,
          fee: true,
        },
      },
    },
  } as const);

....
```
 - typegen.json
 
```
{
  "outDir": "src/types",
  "specVersions": "aleph-zero",
  "events": [
    "Balances.Transfer"
  ],
  "calls": [ 
  ],
  "storage": [
  ]
}
```

** Issue after running `sqd process` **

```
11:10:24 INFO  sqd:processor processing blocks from 0
11:10:25 FATAL sqd:processor HttpError: Got 404 from https://v2.archive.subsquid.io/network/aleph-zero
                                 at ArchiveClient.request (/Users/xxx/my-awesome-squid/node_modules/@subsquid/util-internal-http-client/lib/client.js:45:27)
                                 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                                 at async ArchiveClient.graphqlRequest (/Users/xxx/my-awesome-squid/node_modules/@subsquid/util-internal-http-client/lib/client.js:268:19)
                                 at async Ingest.fetchArchiveHeight (/Users/xxx/my-awesome-squid/node_modules/@subsquid/substrate-processor/lib/ingest.js:228:19)
                                 at async Runner.run (/Users/xxx/my-awesome-squid/node_modules/@subsquid/substrate-processor/lib/processor/runner.js:105:37)
                                 response: {"status":404,"headers":[["access-control-allow-credentials","true"],["access-control-allow-headers","DNT,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range,Authorization"],["access-control-allow-methods","GET, PUT, POST, DELETE, PATCH, OPTIONS"],["access-control-allow-origin","*"],["access-control-max-age","1728000"],["alt-svc","h3=\":443\"; ma=2592000,h3-29=\":443\"; ma=2592000"],["content-length","0"],["date","Wed, 04 Oct 2023 04:10:25 GMT"],["via","1.1 google"]],"url":"https://v2.archive.subsquid.io/network/aleph-zero"}
                                 archiveQuery: query { status { head } }
```

**Comment by ggawryal** [comment]
I got the same error when running on the same subsquid version as there. However, updating to the latest version resolved the issue for me.
