### ISSUE TITLE
FATAL sqd:substrate-typegen Error: Unknown signed extension: OnlyMigrator

### ISSUE THREAD

**Issue by dcolley** [subsquid/squid-sdk#225]
**Describe the bug**
I am trying to index dock PoS mainnet
`sqd typegen` is failing with this error:
```bash
$ sqd typegen
(node:83338) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
TYPEGEN
11:07:44 INFO  sqd:substrate-typegen using ./typegen.json
11:07:44 FATAL sqd:substrate-typegen Error: Unknown signed extension: OnlyMigrator
                                         at FromOld.getSignedExtensionType (/home/derek/subledgr-dock/node_modules/@subsquid/substrate-runtime/lib/metadata/runtime-description.js:485:23)
                                         at FromOld.addSignedExtensionField (/home/derek/subledgr-dock/node_modules/@subsquid/substrate-runtime/lib/metadata/runtime-description.js:456:25)
                                         at /home/derek/subledgr-dock/node_modules/@subsquid/substrate-runtime/lib/metadata/runtime-description.js:444:26
                                         at Array.forEach (<anonymous>)
                                         at FromOld.signedExtensions (/home/derek/subledgr-dock/node_modules/@subsquid/substrate-runtime/lib/metadata/runtime-description.js:443:64)
                                         at FromOld.value (/home/derek/subledgr-dock/node_modules/@subsquid/substrate-runtime/node_modules/@subsquid/util-internal/lib/def.js:20:30)
                                         at Object.GenericSignature (/home/derek/subledgr-dock/node_modules/@subsquid/substrate-runtime/lib/metadata/runtime-description.js:425:36)
                                         at OldTypeRegistry.buildNamedType (/home/derek/subledgr-dock/node_modules/@subsquid/substrate-runtime/lib/metadata/old/typeRegistry.js:226:47)
                                         at OldTypeRegistry.buildScaleType (/home/derek/subledgr-dock/node_modules/@subsquid/substrate-runtime/lib/metadata/old/typeRegistry.js:215:29)
                                         at OldTypeRegistry.use (/home/derek/subledgr-dock/node_modules/@subsquid/substrate-runtime/lib/metadata/old/typeRegistry.js:85:35)

```
**To Reproduce**
1. Extract types using `substrate-metadata-explorer`:
```
npm run build
node bin/run.js --rpc wss://rpc.metaspan.io/dock --out dock-typegen.jsonl
```

2. Generate the dock-typesBundle.json
```bash
npm install --save @docknetwork/node-types
```
create `extract-types.js` file to extract types to json
```
const { spec } = require('@docknetwork/node-types')
const typesBundle = spec['dock-pos-main-runtime'] // .types // .typesBundle
console.debug(JSON.stringify(typesBundle, null, 2))
```
Extract the types
```
node extract-types.js > dock-typesBundle.json
```

3. update typegen.json and run sqd typegen
```json
{
  "outDir": "src/types",
  "specVersions": "./typegen-dock.jsonl",
  "typesBundle": "./dock-typesBundle.json",
  "pallets": {
  // etc...
  }
}
```

**Expected behavior**
typegen should create the types in `src/types`

**Screenshots**
None

**Environment (please complete the following information):**
 - specify the version of the core packages (@subsquid/cli, @subsquid/substrate-processor, ...) 
```json
  "dependencies": {
    "@docknetwork/node-types": "^0.16.0",
    "@subsquid/archive-registry": "^3.3.0",
    "@subsquid/graphql-server": "^4.3.1",
    "@subsquid/ss58": "^2.0.1",
    "@subsquid/substrate-processor": "^7.2.1",
    "@subsquid/typeorm-migration": "^1.2.2",
    "@subsquid/typeorm-store": "^1.2.4",
    "dotenv": "^16.3.1",
    "pg": "8.11.3",
    "typeorm": "^0.3.17"
  },
  "devDependencies": {
    "@subsquid/substrate-metadata-explorer": "^3.1.1",
    "@subsquid/substrate-typegen": "^8.0.1",
    "@subsquid/typeorm-codegen": "^1.3.2",
    "@types/node": "^20.8.4",
    "typescript": "^5.2.2"
  }
```
 - node.js version: v21.6.0 and v18.18.0
 - npm version
 - OS version: ubuntu 23 .04
 - Reproducible example or a repo link: https://github.com/subledgr/subsquid-dock

**Applicable to decoding issues:**
 - chain name: Dock
 - typesBundle (if it's not built-in)
optional:
 - block
 - extrinsic
 - call
 - event
 - spec version
 - endpoint: wss://rpc.metaspan.io/dock

**Comment by belopash** [comment]
Your typesBundle is missing definition of `OnlyMigrator` signed extension. As possible solution you can add the following to the each version in yours bundle
```
"signedExtensions": {
  "OnlyMigrator": {
    extrinsic: {}
  }
} 
```

**Comment by dcolley** [comment]
adding that definition for each `{ "types ": ... }` section has no effect.
adding that definition at root produces this error:

```
06:34:51 FATAL sqd:substrate-typegen Error: Unexpected case
                                         at unexpectedCase (/home/derek/subledgr-dock/node_modules/@subsquid/substrate-runtime/node_modules/@subsquid/util-internal/lib/misc.js:38:12)
                                         at OldTypeRegistry.buildScaleType (/home/derek/subledgr-dock/node_modules/@subsquid/substrate-runtime/lib/metadata/old/typeRegistry.js:222:58)
                                         at OldTypeRegistry.use (/home/derek/subledgr-dock/node_modules/@subsquid/substrate-runtime/lib/metadata/old/typeRegistry.js:85:35)
                                         at FromOld.getSignedExtensionType (/home/derek/subledgr-dock/node_modules/@subsquid/substrate-runtime/lib/metadata/runtime-description.js:464:34)
                                         at FromOld.addSignedExtensionField (/home/derek/subledgr-dock/node_modules/@subsquid/substrate-runtime/lib/metadata/runtime-description.js:456:25)
                                         at /home/derek/subledgr-dock/node_modules/@subsquid/substrate-runtime/lib/metadata/runtime-description.js:444:26
                                         at Array.forEach (<anonymous>)
                                         at FromOld.signedExtensions (/home/derek/subledgr-dock/node_modules/@subsquid/substrate-runtime/lib/metadata/runtime-description.js:443:64)
                                         at FromOld.value (/home/derek/subledgr-dock/node_modules/@subsquid/substrate-runtime/node_modules/@subsquid/util-internal/lib/def.js:20:30)
                                         at Object.GenericSignature (/home/derek/subledgr-dock/node_modules/@subsquid/substrate-runtime/lib/metadata/runtime-description.js:425:36)
```

**Comment by eldargab** [comment]
@dcolley Checkout [here](https://github.com/subsquid/squid-sdk/blob/3fc57fd9395edf77d016ddde191d73bc1fde356a/substrate/substrate-runtime/src/metadata/old/typesBundle-polkadotjs.ts#L17) for expected structure of polkdotjs types bundle.

Also one must check the actual `OnlyMigrator` type and define it accordingly instead of just assuming, that it bears no data.
