### ISSUE TITLE
Support Substrate extrinsic v5

### ISSUE THREAD

**Issue by jasl** [subsquid/squid-sdk#348]
TransactionExtension https://github.com/paritytech/polkadot-sdk/pull/3685 is a major upgrade of Substrate, which bumps the extrinsic version to 5.
Although it still needs a few months to be released to the stable channel,
I would appreciate it if you could schedule to support it.

**Comment by dzhelezov** [comment]
Thanks for the heads up!

**Comment by jasl** [comment]
FYI: The extrinsic v5 spec hasn't finished yet https://github.com/polkadot-fellows/RFCs/pull/124

**Comment by Tbaut** [comment]
Westend who has probably upgraded is now failing with the following:
```bash
23544579 / 23736588, rate: 6 blocks/sec, mapping: 604 blocks/sec, 60 items/sec, eta: 8h 55m
20:18:07 FATAL sqd:processor AssertionError [ERR_ASSERTION]: unsupported extrinsic version
                                 at decodeExtrinsic (/home/thib/Github/ChainSafe/multix/squid/node_modules/@subsquid/substrate-runtime/lib/runtime/extrinsic.js:16:26)
                                 at Runtime.decodeExtrinsic (/home/thib/Github/ChainSafe/multix/squid/node_modules/@subsquid/substrate-runtime/lib/runtime/runtime.js:233:48)
                                 at /home/thib/Github/ChainSafe/multix/squid/node_modules/@subsquid/substrate-data/lib/parsing/extrinsic.js:12:27
                                 at Array.map (<anonymous>)
                                 at decodeExtrinsics (/home/thib/Github/ChainSafe/multix/squid/node_modules/@subsquid/substrate-data/lib/parsing/extrinsic.js:10:23)
                                 at BlockParser.decodedExtrinsics (/home/thib/Github/ChainSafe/multix/squid/node_modules/@subsquid/substrate-data/lib/parsing/block.js:93:49)
                                 at BlockParser.value (/home/thib/Github/ChainSafe/multix/squid/node_modules/@subsquid/substrate-data/node_modules/@subsquid/util-internal/lib/def.js:20:30)
                                 at BlockParser.timestamp (/home/thib/Github/ChainSafe/multix/squid/node_modules/@subsquid/substrate-data/lib/parsing/block.js:121:70)
                                 at BlockParser.value (/home/thib/Github/ChainSafe/multix/squid/node_modules/@subsquid/substrate-data/node_modules/@subsquid/util-internal/lib/def.js:20:30)
                                 at parseBlock (/home/thib/Github/ChainSafe/multix/squid/node_modules/@subsquid/substrate-data/lib/parsing/block.js:35:37)
                                 generatedMessage: false
                                 code: ERR_ASSERTION
                                 actual: false
                                 expected: true
                                 operator: ==
                                 blockHeight: 23544583
                                 blockHash: 0xb095192cfc5cbbcd379cbc511c509b9df411ea1a19f45bca134f7e0d93e58f92
```
